package com.ochafik.lang.jnaerator.nativesupport.dllexport;
/**
 * JNA Wrapper for library <b>DllExport</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface DllExportLibrary extends com.sun.jna.Library {
	public static final com.ochafik.lang.jnaerator.nativesupport.dllexport.DllExportLibrary INSTANCE = (com.ochafik.lang.jnaerator.nativesupport.dllexport.DllExportLibrary)com.sun.jna.Native.loadLibrary(com.ochafik.lang.jnaerator.runtime.LibraryExtractor.getLibraryPath("DllExport", true, com.ochafik.lang.jnaerator.nativesupport.dllexport.DllExportLibrary.class), com.ochafik.lang.jnaerator.nativesupport.dllexport.DllExportLibrary.class, com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper.DEFAULT_OPTIONS);
	/// <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i>
	public static final int IMAGE_DIRECTORY_ENTRY_TLS = 9;
	/// <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i>
	public static final int IMAGE_DIRECTORY_ENTRY_EXCEPTION = 3;
	/// <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i>
	public static final int IMAGE_DIRECTORY_ENTRY_IMPORT = 1;
	/// <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i>
	public static final int IMAGE_DIRECTORY_ENTRY_GLOBALPTR = 8;
	/// <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i>
	public static final int IMAGE_SIZEOF_SHORT_NAME = 8;
	/// <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i>
	public static final int IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT = 13;
	/// <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i>
	public static final int IMAGE_DIRECTORY_ENTRY_BOUND_IMPORT = 11;
	/// <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i>
	public static final int IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR = 14;
	/// <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i>
	public static final int IMAGE_DIRECTORY_ENTRY_IAT = 12;
	/// <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i>
	public static final int IMAGE_DIRECTORY_ENTRY_DEBUG = 6;
	/// <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i>
	public static final int IMAGE_DIRECTORY_ENTRY_RESOURCE = 2;
	/// <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i>
	public static final int IMAGE_DIRECTORY_ENTRY_EXPORT = 0;
	/// <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i>
	public static final int IMAGE_DIRECTORY_ENTRY_BASERELOC = 5;
	/// <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i>
	public static final int IMAGE_DIRECTORY_ENTRY_ARCHITECTURE = 7;
	/// <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i>
	public static final int IMAGE_DIRECTORY_ENTRY_SECURITY = 4;
	/// <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i>
	public static final int IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG = 10;
	/// <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i>
	public static final int IMAGE_NT_SIGNATURE = 17744;
	/// <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i>
	public static final int IMAGE_NUMBEROF_DIRECTORY_ENTRIES = 16;
	/// <i>native declaration : C:\Prog\jnaerator\sources\com\ochafik\lang\jnaerator\nativesupport\dllexport.h</i>
	public static final int IMAGE_DOS_SIGNATURE = 23117;
}
